### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by DoubleTPeter** [robi0t/zzCrack#1]
Am getting a MemoryError. Am running a system with 32GB RAM and 28GB is not used by anything.

Enter a directory/name to a .zip file > test.zip
Which attack type would you like to run
0: Bruteforce    1: Wordlist > 0

[+] Which characters to use in the attack (combine to use multiple, separated by +)
 0: Only small letters
 1: Only big letters
 2: Only numbers
 3: Only signs
 4: Everything

 4

[-+] Max length > 6

Do you want to output everything (slower) or not (faster)  y/n > n
Generating list, Please wait
Traceback (most recent call last):
  File "D:\Desktop\Test\main.py", line 392, in <module>
    _noargs()
  File "D:\Desktop\Test\main.py", line 210, in _noargs
    bruteforce(zip_dir, charset, max_letters, showoutput_b, None)
  File "D:\Desktop\Test\main.py", line 128, in bruteforce
    a = [y + i for i in charlist for y in a]
  File "D:\Desktop\Test\main.py", line 128, in <listcomp>
    a = [y + i for i in charlist for y in a]
MemoryError

D:\Desktop\Test>

**Comment by robi0t** [comment]
This is probably cause you are trying to generate a too big bruteforce list. Try with a smaller max lenght like 4 or another charlist that is smaller.

What you are trying to do right now is to create a list with lenghtofchars^maxlenght which in this case is 100^6 which is basically
1e+12 or straight forward 1,000,000,000,000 combinations

And that is a little bit much for a list

**Comment by Markusnarillious** [comment]
looks like u guys have a issue here...Trying to code someones taxes are you. Can i inspect your work

**Comment by Markusnarillious** [comment]
I put in the work....I merged the update. I looked into your errors. And u still did not even pay me for it. And still trying to follow me around like puppys.

**Comment by robi0t** [comment]
Fixed it :))
